import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight, Check } from 'lucide-react';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import WhatsAppButton from '@/components/ui/WhatsAppButton';
import { CONTACT } from '@/lib/constants';
import { formatCurrency } from '@/lib/formatCurrency';

type Experience = { title: string; category: string; duration: string; capacity: string; startingPrice: number; location: string; overview: string; image: string; imageAlt: string; highlights: string[]; inclusions: string[]; itinerary: { time: string; title: string; desc: string }[] };

const EXPERIENCES: Record<string, Experience> = {
  'yacht-sunset': { title: 'Özel süperyat gün batımı seyri', category: 'Yat & deniz', duration: '4 saat', capacity: '10 kişiye kadar', startingPrice: 6800, location: 'Dubai Marina', image: '/images/luxury-yacht.jpg', imageAlt: 'Dubai Marina önünde gün batımında özel yat', overview: 'Dubai Marina, Ain Dubai ve Palm Jumeirah rotasında profesyonel mürettebat ve özel servis eşliğinde size ait bir gün batımı seyri.', highlights: ['Majesty 56ft yat için özel kiralama', 'Ain Dubai, Palm Jumeirah ve Burj Al Arab rotası', 'Yüzme molası ve gün batımı fotoğraf noktaları'], inclusions: ['Lisanslı kaptan ve servis personeli', 'Yakıt ve marina yanaşma ücretleri', 'Soft içecekler, su ve güvenlik ekipmanları'], itinerary: [{ time: '15:30', title: 'Marina karşılama', desc: 'Pier 7 lounge alanında karşılama ve biniş.' }, { time: '16:00', title: 'Marina’dan çıkış', desc: 'Şehir silüetinin arasından açık denize seyir.' }, { time: '17:30', title: 'Palm Jumeirah', desc: 'Gün batımı, ikramlar ve yüzme molası.' }, { time: '19:30', title: 'Marina’ya dönüş', desc: 'Gece ışıkları eşliğinde iskeleye dönüş.' }] },
  'desert-safari': { title: 'VIP kızıl kum çöl safarisi', category: 'Çöl & macera', duration: '6 saat', capacity: '1–6 kişilik özel araç', startingPrice: 4200, location: 'Lahbab Çölü', image: '/images/desert-safari.jpg', imageAlt: 'Gün batımında Lahbab çölünde özel kamp ve safari aracı', overview: 'Kalabalıktan uzakta, özel araçla kızıl kum tepeleri ve size ayrılan Majlis kampında akşam yemeğiyle tamamlanan bir çöl deneyimi.', highlights: ['Özel 4x4 araç ile safari', 'Kızıl kum tepelerinde sandboarding', 'Size ayrılan Majlis alanı'], inclusions: ['Otelden özel transfer', 'Çöl rehberi ve safari uzmanı', 'Akşam yemeği ve geleneksel ikramlar'], itinerary: [{ time: '15:00', title: 'Otelden alınış', desc: 'Özel 4x4 araçla hareket.' }, { time: '16:15', title: 'Kızıl kum safarisi', desc: 'Kum tepeleri, sandboarding ve fotoğraf molası.' }, { time: '18:00', title: 'Majlis kampı', desc: 'Gün batımı ikramları ve kamp deneyimi.' }, { time: '19:30', title: 'Akşam yemeği', desc: 'Yıldızların altında servis.' }] },
  'helicopter-tour': { title: 'Dubai helikopter şehir turu', category: 'Havacılık', duration: '25 dakika', capacity: '6 kişiye kadar', startingPrice: 3600, location: 'Palm Jumeirah', image: '/images/hero-skyline.jpg', imageAlt: 'Burj Khalifa ve Downtown Dubai şehir silüeti', overview: 'Palm Jumeirah’dan Downtown’a Dubai’nin en ikonik yapılarını gökyüzünden izleyen panoramik bir şehir rotası.', highlights: ['Palm Jumeirah ve The World Islands görünümü', 'Burj Al Arab ve Downtown rotası', 'VIP helipad lounge karşılama'], inclusions: ['Uçuş öncesi güvenlik brifingi', 'Profesyonel pilot anlatımı', 'Gerekli hava sahası ve operasyon ücretleri'], itinerary: [{ time: '10:15', title: 'Helipad karşılama', desc: 'Kontrol ve uçuş öncesi brifing.' }, { time: '10:45', title: 'Palm Jumeirah', desc: 'Kalkış ve ada üzerinde panoramik uçuş.' }, { time: '11:00', title: 'Downtown', desc: 'Burj Khalifa ve şehir silüeti geçişi.' }, { time: '11:15', title: 'İniş', desc: 'Helipad’e dönüş.' }] },
};

export function generateStaticParams() { return Object.keys(EXPERIENCES).map(slug => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = EXPERIENCES[slug]; return item ? { title: `${item.title} | Travia Dubai`, description: item.overview } : {}; }

export default async function ExperienceDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const item = EXPERIENCES[slug];
  if (!item) notFound();
  const whatsapp = `${CONTACT.whatsappUrl}?text=${encodeURIComponent(`Merhaba, “${item.title}” deneyimi hakkında bilgi almak istiyorum.`)}`;

  return <div className="site-shell min-h-screen"><Navbar /><main>
    <section className="relative min-h-[78svh] overflow-hidden" aria-labelledby="experience-title"><Image src={item.image} alt={item.imageAlt} fill loading="eager" fetchPriority="high" sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,10,9,.92),rgba(3,10,9,.25)_70%),linear-gradient(180deg,transparent_45%,rgba(3,10,9,.9))]" /><div className="container-wide relative z-10 flex min-h-[78svh] flex-col justify-end pb-12 pt-28"><Link href="/#gallery" className="mb-auto inline-flex min-h-11 w-fit items-center gap-2 text-[.65rem] font-bold uppercase tracking-[.14em] text-ivory/70"><ArrowLeft className="size-4" /> Deneyimlere dön</Link><p className="eyebrow">{item.category}</p><h1 id="experience-title" className="display title-lg mt-6 max-w-[12ch]">{item.title}</h1><p className="mt-7 max-w-2xl text-sm leading-7 text-ivory/68 sm:text-base">{item.overview}</p></div></section>
    <section className="paper-section section-space"><div className="container-wide"><dl className="grid border-y border-[#0b1513]/18 sm:grid-cols-2 lg:grid-cols-4">{[['Süre',item.duration],['Kapasite',item.capacity],['Lokasyon',item.location],['Başlangıç',formatCurrency(item.startingPrice)]].map(([term,value],index) => <div key={term} className={`py-6 ${index ? 'sm:border-l sm:border-[#0b1513]/18 sm:pl-6' : ''}`}><dt className="text-[.58rem] font-bold uppercase tracking-[.15em] text-[#80673f]">{term}</dt><dd className="mt-2 font-serif text-2xl">{value}</dd></div>)}</dl>
      <div className="mt-16 grid gap-14 lg:grid-cols-12"><div className="lg:col-span-7"><p className="eyebrow">Deneyimin özü</p><div className="mt-8 grid gap-10 sm:grid-cols-2"><div><h2 className="font-serif text-3xl">Öne çıkanlar</h2><ul className="mt-6 space-y-4">{item.highlights.map(text => <li key={text} className="flex gap-3 text-sm leading-6 text-[#0b1513]/68"><Check className="mt-1 size-3.5 shrink-0 text-[#80673f]" />{text}</li>)}</ul></div><div><h2 className="font-serif text-3xl">Dahil olanlar</h2><ul className="mt-6 space-y-4">{item.inclusions.map(text => <li key={text} className="flex gap-3 text-sm leading-6 text-[#0b1513]/68"><Check className="mt-1 size-3.5 shrink-0 text-[#80673f]" />{text}</li>)}</ul></div></div>
        <div className="mt-16"><h2 className="display text-5xl">Örnek akış</h2><ol className="mt-8 border-t border-[#0b1513]/18">{item.itinerary.map(entry => <li key={entry.time} className="grid gap-2 border-b border-[#0b1513]/18 py-6 sm:grid-cols-[5rem_1fr_1.5fr]"><span className="text-xs font-bold text-[#80673f]">{entry.time}</span><strong className="font-serif text-xl font-medium">{entry.title}</strong><p className="text-sm leading-6 text-[#0b1513]/55">{entry.desc}</p></li>)}</ol></div></div>
        <aside className="lg:col-span-4 lg:col-start-9"><div className="sticky top-28 bg-[#0b1513] p-7 text-ivory sm:p-9"><p className="text-[.6rem] font-bold uppercase tracking-[.17em] text-sand">Private booking</p><p className="display mt-5 text-5xl">{formatCurrency(item.startingPrice)}</p><p className="mt-3 text-xs text-ivory/45">Tarih ve müsaitliğe göre netleşen başlangıç bedeli.</p><a href={whatsapp} target="_blank" rel="noopener noreferrer" className="btn-primary mt-8 w-full">Concierge’e sorun <ArrowUpRight className="size-4" /></a><Link href="/#trip-planner" className="btn-quiet mt-3 w-full">Planıma ekle</Link></div></aside></div>
    </div></section>
  </main><WhatsAppButton /><Footer /></div>;
}
